# fly.toml file generated for tg-channel-forward-bot on 2023-05-15T19:45:26-05:00

app = "tg-channel-forward-bot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  processes = ["app"]

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

